### ISSUE TITLE
Can this project really run normally? I see a lot of things in the issue that say this project can't work

### ISSUE THREAD

**Issue by percy4** [dan-crdll/nn_project_dreamdiffusion#1]

**Comment by dan-crdll** [comment]
What do you mean?
this project is the reimplementation of a paper, I AM NOT the original author of the paper.

Though, only the pretraining part of the work has been implemented and you can try it yourself by running the notebook

**Comment by percy4** [comment]
thank you. I mean a lot of people on the github project of the original paper said that the project was unachievable. Now I want to run this project again

> What do you mean? 你说什么？ this project is the reimplementation of a paper, I AM NOT the original author of the paper. 这个项目是一篇论文的重新实现，我不是论文的原作者。
> 
> Though, only the pretraining part of the work has been implemented and you can try it yourself by running the notebook不过，只有预训练部分的工作已经实现，你可以尝试自己运行的笔记本电脑

**Comment by percy4** [comment]
> What do you mean? 你说什么？ this project is the reimplementation of a paper, I AM NOT the original author of the paper. 这个项目是一篇论文的重新实现，我不是论文的原作者。
> 
> Though, only the pretraining part of the work has been implemented and you can try it yourself by running the notebook不过，只有预训练部分的工作已经实现，你可以尝试自己运行的笔记本电脑

Can you run the original author's github repository of dreamdiffusion?

**Comment by dan-crdll** [comment]
This issue is not related to my repository
